import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { toast } from "react-toastify";
import Pagination from "../Pagination";
import ErrorState from "../ErrorState";

const PAGE_SIZE = 8;
export default function ResourceTable({ title, description, columns, load, createItem, updateItem, deleteItem, emptyItem }) {
  const [items,setItems]=useState([]), [status,setStatus]=useState("loading"), [error,setError]=useState(""), [query,setQuery]=useState(""), [page,setPage]=useState(1), [editing,setEditing]=useState(null);
  const refresh=async()=>{setStatus("loading");try{setItems(await load());setStatus("success");}catch(e){setError(e.message);setStatus("error");}};
  useEffect(()=>{refresh();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const filtered=useMemo(()=>items.filter(item=>Object.values(item).join(" ").toLowerCase().includes(query.toLowerCase())),[items,query]);
  const visible=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  const save=async(e)=>{e.preventDefault();const form=Object.fromEntries(new FormData(e.currentTarget));try{if(editing.id){const saved=await updateItem(editing.id,form);setItems(v=>v.map(x=>x.id===editing.id?{...x,...saved,...form}:x));toast.success(`${title.slice(0,-1)} updated`);}else{const saved=await createItem(form);setItems(v=>[{...form,...saved,id:saved.id||Date.now()},...v]);toast.success(`${title.slice(0,-1)} created`);}setEditing(null);}catch(err){toast.error(err.message);}};
  const remove=async(item)=>{if(!confirm(`Delete ${item.name||item.username||item.title}?`))return;try{await deleteItem(item.id);setItems(v=>v.filter(x=>x.id!==item.id));toast.success("Deleted successfully");}catch(err){toast.error(err.message);}};
  return <section><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="font-display text-3xl font-semibold">{title}</h1><p className="mt-1 text-sm text-charcoal-soft">{description}</p></div><button onClick={()=>setEditing({...emptyItem})} className="flex items-center gap-2 rounded-xl bg-paprika px-4 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Add {title.slice(0,-1)}</button></div>
    <div className="mb-4 max-w-sm relative"><Search className="absolute left-3 top-3 h-4 w-4 text-charcoal-soft"/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder={`Search ${title.toLowerCase()}…`} className="w-full rounded-xl border border-line bg-white py-2.5 pl-10 pr-3 text-sm outline-none focus:border-paprika"/></div>
    {status==="loading"&&<div className="skeleton h-72 rounded-2xl"/>}{status==="error"&&<ErrorState message={error} onRetry={refresh}/>} {status==="success"&&<div className="overflow-hidden rounded-2xl border border-line bg-white"><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-cream-dim/60 text-xs uppercase tracking-wide text-charcoal-soft"><tr>{columns.map(c=><th key={c.key} className="px-5 py-4">{c.label}</th>)}<th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-line">{visible.map(item=><tr key={item.id} className="hover:bg-cream/60">{columns.map(c=><td key={c.key} className="max-w-56 truncate px-5 py-4">{c.render?c.render(item):String(item[c.key]??"—")}</td>)}<td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={()=>setEditing(item)} className="rounded-lg border border-line p-2"><Pencil className="h-4 w-4"/></button><button onClick={()=>remove(item)} className="rounded-lg border border-line p-2 text-paprika"><Trash2 className="h-4 w-4"/></button></div></td></tr>)}</tbody></table></div><div className="px-5 pb-5"><Pagination page={page} total={filtered.length} pageSize={PAGE_SIZE} onChange={setPage}/></div></div>}
    {editing&&<div className="fixed inset-0 z-[60] flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-cream p-6"><div className="mb-5 flex justify-between"><h2 className="font-display text-2xl font-semibold">{editing.id?"Edit":"Add"} {title.slice(0,-1)}</h2><button onClick={()=>setEditing(null)}><X/></button></div><form onSubmit={save} className="space-y-4">{columns.filter(c=>c.editable!==false).map(c=><label key={c.key} className="block text-sm font-medium">{c.label}<input name={c.key} defaultValue={editing[c.key]??""} required={c.required!==false} className="mt-1.5 w-full rounded-xl border border-line bg-white px-4 py-3 outline-none focus:border-paprika"/></label>)}<button className="w-full rounded-xl bg-charcoal py-3 font-semibold text-cream">Save changes</button></form></div></div>}
  </section>;
}
